Repository NappingWhenWeShouldBeZapping/zapp, pull requests merged in 2025-03, with the labels that each got.

#1 Terraform
  .github/workflows/db-pipeline-v1.yml
  .github/workflows/ecr-push.yml
  project_scaffolding_server/src/main/resources/application.properties
  terraform/fargate.tf
Labels: enhancement

#5 Flyway migrations
  .github/workflows/ecr-push.yml
  project_scaffolding_server/pom.xml
  project_scaffolding_server/src/main/resources/application.properties
  project_scaffolding_server/src/main/resources/db/migrations/.gitkeep
  project_scaffolding_server/src/main/resources/db/migrations/V1__CREATEDB.sql
  project_scaffolding_server/src/main/resources/db/migrations/V2__INSERTDATA.sql
  project_scaffolding_server/src/main/resources/db/migrations/select.sql
  terraform/ecr.tf
  terraform/fargate.tf
  terraform/secrets.tf
Labels: enhancement

#7 updates
  .github/workflows/ecr-push.yml
Labels: enhancement

#9 Build cli
  .github/workflows/build-cli.yml
  terraform/secrets.tf
Labels: enhancement

#10 Update ecr workflow
  .github/workflows/ecr-push.yml
  project_scaffolding_server/src/main/resources/application.properties
Labels: bug

#16 Fix migrations
  project_scaffolding_server/pom.xml
  project_scaffolding_server/src/main/resources/application.properties
Labels: bug

#18 Fix scaff commands
  cli/src/main/java/com/scaffoldcli/zapp/CLICommand.java
  cli/src/main/java/com/scaffoldcli/zapp/ZappApplication.java
  cli/src/main/java/com/scaffoldcli/zapp/auth/AuthDetails.java
  cli/src/main/java/com/scaffoldcli/zapp/auth/AutheticateUser.java
  cli/src/main/java/com/scaffoldcli/zapp/auth/Controller.java
  cli/src/main/java/com/scaffoldcli/zapp/commands/Command.java
  cli/src/main/java/com/scaffoldcli/zapp/commands/CreateScaffCommand.java
  cli/src/main/java/com/scaffoldcli/zapp/commands/Init.java
  cli/src/main/java/com/scaffoldcli/zapp/exceptions/UserNotAuthenticatedException.java
  cli/src/main/java/com/scaffoldcli/zapp/lib/Text.java
  cli/src/main/java/com/scaffoldcli/zapp/models/GetScaffOptionsResponse.java
  cli/src/main/java/com/scaffoldcli/zapp/models/GetScaffsResponse.java
  cli/src/main/java/com/scaffoldcli/zapp/net/ZappAPIRequest.java
  cli/src/main/resources/application.properties
  cli/src/test/java/com/scaffoldcli/zapp/AuthenticateUserTest.java
  project_scaffolding_server/src/main/java/com/levelUp2/project_scaffolding_server/control/AuthInterceptor.java
  project_scaffolding_server/src/main/java/com/levelUp2/project_scaffolding_server/control/ScaffController.java
  project_scaffolding_server/src/main/java/com/levelUp2/project_scaffolding_server/db/repo/ScaffRepo.java
  project_scaffolding_server/src/main/java/com/levelUp2/project_scaffolding_server/db/service/ScaffService.java
  project_scaffolding_server/src/main/java/com/levelUp2/project_scaffolding_server/models/CreateScaffRequest.java
  project_scaffolding_server/src/main/resources/application.properties
Labels: bug, enhancement
